# catalog-info.yaml in your GitHub repository (e.g., davewins/OrderProcessingApplication)

# --- ENTITY 1: Component (Your Application) ---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: OrderProcessingApplication
  description: A BusinessWorks application responsible for processing customer orders, interacting with TIBCO EMS and a transactional database.
  annotations:
    github.com/project-slug: davewins/OrderProcessingApplication
    backstage.io/techdocs-ref: dir:.
    tibco.com/bwce-version: 6.x.x
    tibco.com/ems-connection-factory: "OrderProcessingCF"
  tags:
    - tibco
    - businessworks
    - integration
    - order-processing
    - ems
    - database
spec:
  type: service
  lifecycle: production
  owner: group:default/order-processing-team
  system: order-management-system # Reference to the System defined below
  domain: sales-operations # Reference to the Domain defined below
  dependsOn:
    - resource:default/tibco-ems-broker-1 # Reference to the EMS Resource defined below
    - resource:default/order-database-primary # Reference to the Database Resource defined below
  # consumesApis:
  #   - api:default/payment-gateway-api
  providesApis:
    - order-processing-api # Reference to the API defined below

---
# --- ENTITY 2: Resource (TIBCO EMS Broker) ---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tibco-ems-broker-1
  description: Primary TIBCO EMS Broker for order processing queues.
  # Namespace is optional, defaults to 'default' if not specified
  # namespace: default
  annotations:
    tibco.com/ems-url: "tcp://localhost:7222"
  tags:
    - tibco
    - ems
    - messaging
spec:
  type: messaging-broker # You can define custom resource types
  owner: group:default/middleware-team
  system: messaging-infrastructure # Example: EMS could belong to a separate messaging system
  # Relates to the Domain if applicable
  domain: enterprise-integration

---
# --- ENTITY 3: Resource (Order Database) ---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-database-primary
  description: PostgreSQL database for storing order data.
  # namespace: default
  annotations:
    db.com/connection-string: "jdbc:postgresql://orderdb:5432/orders"
    db.com/type: "postgresql"
  tags:
    - database
    - postgresql
    - orders
spec:
  type: database
  owner: group:default/data-platform-team
  system: order-management-system # This database is part of the Order Management System
  domain: sales-operations

---
# --- ENTITY 4: System (Order Management System) ---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: order-management-system
  description: Orchestrates the end-to-end processing and fulfillment of customer orders.
  # namespace: default
  tags:
    - order-management
    - core-business
spec:
  owner: group:default/sales-operations-lead # The team or person responsible for the whole system
  domain: sales-operations # Reference to the Domain defined below

---
# --- ENTITY 5: Domain (Sales Operations) ---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: sales-operations
  description: Represents the business domain encompassing all sales and order fulfillment activities.
  # namespace: default
  tags:
    - business-domain
    - sales
    - operations
spec:
  owner: group:default/business-leadership # The higher-level owner for this domain

---
# You might also add Group entities if they are not already in your Backstage catalog.
# --- ENTITY 6: Group (Order Processing Team) ---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: order-processing-team
  description: The team responsible for developing and maintaining the order processing applications.
spec:
  type: team
  profile:
     displayName: Order Processing Team
     email: order.processing@example.com
     picture: https://example.com/team-icons/order-processing.png
  parent: default/development-department # If you have a hierarchy of groups
  children: [] # List child groups/users if any
  members: # List members by their User entity name
     - user:default/davewins
     - user:default/another-dev

---
#
# --- ENTITY 7: Group (Middleware Team) ---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: middleware-team
  description: Team managing shared middleware services like TIBCO EMS.
spec:
  type: team
  profile:
    displayName: Middleware Team
    email: middleware@example.com
  parent: default/platform-engineering # Example parent group
  children: []
  members:
    - user:default/middleware-engineer1

---
# --- ENTITY 7: API (Order Processing API) ---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: order-processing-api
  description: API for placing and managing customer orders.
  # namespace: default
  tags:
    - order-processing
    - api
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: group:default/order-processing-team
  definition: |
    {
      "swagger" : "2.0",
      "info" : {
        "version" : "1.0",
        "title" : "OrderProcessing"
      },
      "host" : "bwce.vewins.co.uk:443",
      "basePath" : "/tibco/apps/d0mrfgqd9jcaeh9qlih0/Orders",
      "schemes" : [ "https" ],
      "consumes" : [ "application/json" ],
      "produces" : [ "application/json" ],
      "paths" : {
        "/api/orders/customer/{customerId}" : {
          "get" : {
            "tags" : [ "Orders" ],
            "summary" : "Retrieve all orders for a specific customer.",
            "parameters" : [ {
              "name" : "customerId",
              "in" : "path",
              "description" : "Identifier of the customer to retrieve orders for.",
              "required" : true,
              "type" : "string"
            } ],
            "responses" : {
              "200" : {
                "description" : "List of customer orders retrieved successfully.",
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "$ref" : "#/definitions/Order"
                  }
                }
              },
              "500" : {
                "description" : "Internal server error (e.g., simulated database failure).",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              },
              "404" : {
                "description" : "Customer not found (if you choose to implement this level of simulation).",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              }
            }
          }
        },
        "/api/orders" : {
          "post" : {
            "tags" : [ "Orders" ],
            "summary" : "Place a new order.",
            "parameters" : [ {
              "in" : "body",
              "name" : "OrderRequest",
              "description" : "Order details to create.",
              "required" : true,
              "schema" : {
                "$ref" : "#/definitions/OrderRequest"
              }
            } ],
            "responses" : {
              "200" : {
                "description" : "Sample Description",
                "schema" : {
                  "$ref" : "#/definitions/OrderCreationResponse"
                }
              },
              "400" : {
                "description" : "Invalid request payload.",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              },
              "500" : {
                "description" : "Internal server error (e.g., simulated backend failure).",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              }
            }
          }
        },
        "/api/orders/{orderId}" : {
          "get" : {
            "tags" : [ "Orders" ],
            "summary" : "Retrieve details of a specific order.",
            "parameters" : [ {
              "name" : "orderId",
              "in" : "path",
              "description" : "Identifier of the order to retrieve.",
              "required" : true,
              "type" : "string"
            } ],
            "responses" : {
              "500" : {
                "description" : "Internal server error (e.g., simulated database failure).",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              },
              "404" : {
                "description" : "Order not found.",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              },
              "200" : {
                "description" : "Order details retrieved successfully.",
                "schema" : {
                  "$ref" : "#/definitions/Order"
                }
              }
            }
          },
          "put" : {
            "tags" : [ "Orders" ],
            "summary" : "Update the status of an existing order.",
            "parameters" : [ {
              "name" : "orderId",
              "in" : "path",
              "description" : "Identifier of the order to retrieve.",
              "required" : true,
              "type" : "string"
            }, {
              "in" : "body",
              "name" : "OrderStatusUpdateRequest",
              "description" : "New status for the order.",
              "required" : true,
              "schema" : {
                "$ref" : "#/definitions/OrderStatusUpdateRequest"
              }
            } ],
            "responses" : {
              "500" : {
                "description" : "Internal server error (e.g., simulated backend failure).",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              },
              "200" : {
                "description" : "Order status updated successfully."
              },
              "404" : {
                "description" : "Order not found.",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              },
              "400" : {
                "description" : "Invalid request payload.",
                "schema" : {
                  "$ref" : "#/definitions/ErrorResponse"
                }
              }
            }
          }
        }
      },
      "definitions" : {
        "Product" : {
          "type" : "object",
          "properties" : {
            "name" : {
              "type" : "string",
              "description" : "Name of the product."
            },
            "quantity" : {
              "type" : "integer",
              "description" : "Quantity of the product ordered.",
              "minimum" : 1
            }
          }
        },
        "OrderRequest" : {
          "type" : "object",
          "required" : [ "customerId", "products" ],
          "properties" : {
            "customerId" : {
              "type" : "string",
              "description" : "Identifier of the customer placing the order."
            },
            "products" : {
              "type" : "array",
              "description" : "List of products in the order.",
              "items" : {
                "$ref" : "#/definitions/Product"
              }
            }
          }
        },
        "Order" : {
          "type" : "object",
          "properties" : {
            "orderId" : {
              "type" : "string",
              "description" : "Unique identifier of the order.",
              "readOnly" : true
            },
            "customerId" : {
              "type" : "string",
              "description" : "Identifier of the customer."
            },
            "orderDate" : {
              "type" : "string",
              "format" : "date-time",
              "description" : "Date and time the order was placed.",
              "readOnly" : true
            },
            "products" : {
              "type" : "array",
              "description" : "List of products in the order.",
              "items" : {
                "$ref" : "#/definitions/Product"
              }
            },
            "status" : {
              "type" : "string",
              "description" : "Current status of the order.",
              "enum" : [ "Pending", "Processing", "Shipped", "Cancelled" ]
            }
          }
        },
        "OrderStatusUpdateRequest" : {
          "type" : "object",
          "required" : [ "status" ],
          "properties" : {
            "status" : {
              "type" : "string",
              "description" : "New status for the order.",
              "enum" : [ "Processing", "Shipped", "Cancelled" ]
            }
          }
        },
        "ErrorResponse" : {
          "type" : "object",
          "properties" : {
            "code" : {
              "type" : "integer",
              "description" : "Error code."
            },
            "message" : {
              "type" : "string",
              "description" : "Error message."
            }
          }
        },
        "OrderCreationResponse" : {
          "type" : "object",
          "properties" : {
            "orderId" : {
              "type" : "string",
              "description" : "The newly created order ID."
            }
          }
        }
      }
    }