apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: OrderProcessingApplication
  annotations:
    github.com/project-slug: davewins/OrderProcessingApplication
spec:
  type: other
  lifecycle: unknown
  owner: tibco-imported
