# catalog-info.yaml for TIBCO EMS Broker
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tibco-ems-broker-1
  description: Primary TIBCO EMS Broker for order processing queues.
  annotations:
    # Example: EMS server URL
    tibco.com/ems-url: "tcp://localhost:7222"
spec:
  type: messaging-broker
  owner: group:default/middleware-team
  system: messaging-infrastructure
  # Consider adding environment specific details if applicable
  # For example, if you have different EMS brokers for different environments (dev, prod)
---
# catalog-info.yaml for Order Database
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: order-database-primary
  description: PostgreSQL database for storing order data.
  annotations:
    # Example: Database connection string fragment
    db.com/connection-string: "jdbc:postgresql://orderdb:5432/orders"
    db.com/type: "postgresql"
spec:
  type: database
  owner: group:default/data-platform-team
  system: order-management-system